version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
#      - postgres_data:/var/lib/postgresql/data/
#    environment:
#      - POSTGRES_USER=${POSTGRES_USER}
#      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#      - POSTGRES_DB=${POSTGRES_DB}
#    healthcheck:
#      test: ["CMD-SHELL", "pg_isready -U rico -d tasks"]
#      interval: 1s
    extends:
      file: postgres.yaml
      service: postgres

#  web:
#    build: .
#    ports:
#      - "8080:8080"
#    depends_on:
#      postgres:
#        condition: service_healthy
##    depends_on:
##      - postgres
#    environment:
#      - POSTGRES_USER=${POSTGRES_USER}
#      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#      - POSTGRES_DB=${POSTGRES_DB}
#      - POSTGRES_HOST=${POSTGRES_HOST}
#      - POSTGRES_PORT=${POSTGRES_PORT}